name: Build (CI)

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: |
          npm install
          npm run bootstrap

      - name: Install jest
        run: npm install jest@^26.0.15

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
