name: Publish (CI)

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  testAndPublish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Git Identity
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci@bots.skyslit.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check NPM Registry Access
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: |
          npm install
          npm run bootstrap
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install jest
        run: npm install jest@^26.0.15 -g
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install lerna
        run: npm install lerna@^3.22.1 -g
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test
        run: npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: lerna publish --conventional-commits --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
