name: Test

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Git Identity
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci@bots.skyslit.com'

      - name: Install Dependencies
        run: |
          npm install
          npm run bootstrap

      - name: Install jest
        run: npm install jest@^27.0.4

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
